<template>
    <div class="loadingio-spinner-double-ring-mrlk94a5jbr"><div class="ldio-kpv33koa5db">
        <div></div>
        <div></div>
        <div><div></div></div>
        <div><div></div></div>
    </div></div>
</template>

<style>
@keyframes ldio-kpv33koa5db {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-kpv33koa5db div { box-sizing: border-box!important }
.ldio-kpv33koa5db > div {
  position: absolute;
  width: 40.97px;
  height: 40.97px;
  top: 100.015px;
  left: 100.015px;
  border-radius: 50%;
  border: 2.41px solid #000;
  border-color: #59A4BD transparent #59A4BD transparent;
  animation: ldio-kpv33koa5db 1.6949152542372883s linear infinite;
}

.ldio-kpv33koa5db > div:nth-child(2), .ldio-kpv33koa5db > div:nth-child(4) {
  width: 31.330000000000002px;
  height: 31.330000000000002px;
  top: 104.83500000000001px;
  left: 104.83500000000001px;
  animation: ldio-kpv33koa5db 1.6949152542372883s linear infinite reverse;
}
.ldio-kpv33koa5db > div:nth-child(2) {
  border-color: transparent #ffffff transparent #ffffff;
}
.ldio-kpv33koa5db > div:nth-child(3) { border-color: transparent }
.ldio-kpv33koa5db > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-kpv33koa5db > div:nth-child(3) div:before, .ldio-kpv33koa5db > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 2.41px;
  height: 2.41px;
  top: -2.41px;
  left: 16.87px;
  background: #59A4BD;
  border-radius: 50%;
  box-shadow: 0 38.56px 0 0 #59A4BD;
}
.ldio-kpv33koa5db > div:nth-child(3) div:after {
  left: -2.41px;
  top: 16.87px;
  box-shadow: 38.56px 0 0 0 #59A4BD;
}

.ldio-kpv33koa5db > div:nth-child(4) { border-color: transparent; }
.ldio-kpv33koa5db > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-kpv33koa5db > div:nth-child(4) div:before, .ldio-kpv33koa5db > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 2.41px;
  height: 2.41px;
  top: -2.41px;
  left: 12.05px;
  background: #774023;
  border-radius: 50%;
  box-shadow: 0 28.92px 0 0 #774023;
}
.ldio-kpv33koa5db > div:nth-child(4) div:after {
  left: -2.41px;
  top: 12.05px;
  box-shadow: 28.92px 0 0 0 #774023;
}
.loadingio-spinner-double-ring-mrlk94a5jbr {
  width: 241px;
  height: 241px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f300;
}
.ldio-kpv33koa5db {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kpv33koa5db div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>